# Generated by Django 5.1.1 on 2024-10-08 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_menu_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_data',
        ),
        migrations.DeleteModel(
            name='Register_data',
        ),
    ]
